wip

diff --git a/scripts/target/sbin/cowroot-checkout b/scripts/target/sbin/cowroot-checkout
--- a/scripts/target/sbin/cowroot-checkout
+++ b/scripts/target/sbin/cowroot-checkout
@@ -3,75 +3,69 @@
 #
 #
 #
-#
+# echo something 1>&2
 #
 
 set -e
 
-opts=ro
-replace=
+source cowroot-env
+source $SYSTEM_ENV
+source $RUNTIME_ENV
 
-while getopts ":rw" o; do
+if  # ab|ab
+  [ "$loader_l" == "$system_l" ] &&
+  [ "$loader_r" == "$system_r" ] &&
+  [ "$loader_l" != "$loader_r" ]; then
+  echo "forbidden" 1>&2
+  exit 1
+fi
+
+# not _a|a_ (aka, neither _a|aa nor _a|ab)
+if [ "$loader_r" != "$system_l" ]; then
+  echo "internal error" 1>&2
+  exit 1
+fi
+
+while getopts ":m:" o; do
   case "${o}" in
-    r)
-      replace=true
-      ;;
-    w)
-      opts=rw
+    m)
+      opts=${OPTARG}
       ;;
     *)
-      echo "usage:"
-      echo "  cowroot-checkout [-w] <subvolume uuid b>        # _a|aa -> _a|ab"
-      echo "  cowroot-checkout -r [-w] <subvolume uuid c>     # _a|ab -> _a|ac"
-      echo "  cowroot-checkout -r                             # _a|ab -> _a|aa"
+      echo "invalid args" 1>&2
+      echo "usage: cowroot-checkout [-m [ro || rw]] [uuid]"
       exit 1
       ;;
   esac
 done
 shift $((OPTIND-1))
 
-source cowroot-env
-source $SYSTEM_ENV
-source $RUNTIME_ENV
+if [ -z $opts ]; then
+  echo "invalid args" 1>&2
+  echo "mode not set"
+elif [ $opts != ro ] && [ $opts != rw ]; then
+  echo "invalid args" 1>&2
+  echo "mode can only be ro or rw"
+fi
 
-if [ ${loader_r} == ${system_l} ]; then 
-  if [ ${system_l} == ${system_r} ]; then
-    subvol_uuid=$1 
-  else 
-    if [ -z $replace ]; then
-      echo "-r required for _a|ab"
-      exit 1
-    fi
-    
-    if [ -z $1 ]; then
-      subvol_uuid=$system_l
-      opts=$system_l_opts
-    else
-      subvol_uuid=$1
-    fi
-  fi
-
-  if [ -z $subvol_uuid ]; then
-    echo "subvolume uuid not provided" 
+if [ "$1" ]; then
+  if [[ "$1" =~ ^${UUID_REGEX} ]]; then
+    uuid=$1    
+  else
+    echo "invalid args" 1>&2
+    echo "not a uuid: $1"
     exit 1
-  fi
- 
-  if [ ! -d $RO_SUBVOL_DIR/$subvol_uuid ]; then
-    echo "subvolume uuid ${subvol_uuid} not found in ro-subvolume directory" 
-    exit 1
-  fi
+else 
+  uuid=$system_r
+fi
 
 cat > $SYSTEM_TMP << EOF
 system_l=$system_l
 system_l_opts=$system_l_opts
-system_r=$system_r
-system_r_opts=$system_r_opts
+system_r=$uuid
+system_r_opts=$opts
 EOF
 
-  mv $SYSTEM_TMP $SYSTEM_ENV
+mv $SYSTEM_TMP $SYSTEM_ENV
 
-else
-  echo "neither _a|aa nor _a|ab, operation not allowed"
-  exit 1
-fi
-
+echo "success"
